// app/layout.tsx

import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { ThemeProvider } from "@mui/material/styles";
import CssBaseline from "@mui/material/CssBaseline";
import theme from "../src/styles/theme"; // Import your custom theme
import "./globals.css";
import { ProductProvider } from "../src/contexts/ProductContext"; // Import ProductProvider

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Inventory",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        {/* Wrap your application with ProductProvider to provide the context */}
        <ProductProvider>
          <ThemeProvider theme={theme}>
            <CssBaseline /> {/* Apply the theme's baseline styles */}
            {children}
          </ThemeProvider>
        </ProductProvider>
      </body>
    </html>
  );
}
