// app/layout.tsx

import type { Metadata } from "next";
import { Inter } from "next/font/google";
import RootLayoutClient from "./RootLayoutClient"; // Import the client component

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Inventory",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        {/* Pass children directly to the client component */}
        <RootLayoutClient>{children}</RootLayoutClient>
      </body>
    </html>
  );
}
